---
- node:
    id: awx-task

- control-service:
    service: control
    filename: /tmp/receptor.sock

- tcp-listener:
    port: 27199

- work-command:
    worktype: local
    command: /var/lib/awx/venv/awx/bin/ansible-runner
    params: worker
    allowruntimeparams: true

- log-level:
    level: info
