---
- node:
    id: awxtask

- log-level:
    level: info

- control-service:
    service: control
    filename: /tmp/receptor/receptor.sock
    permissions: "0660"

- tcp-listener:
    port: 27199

- work-command:
    worktype: local
    command: /tmp/ansible-runner-wrapper.sh
    params: worker
    allowruntimeparams: true
